server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://book-service:8081/
          predicates:
            - Path=/api/v1/books/**

        - id: member-service
          uri: http://member-service:8082/
          predicates:
            - Path=/api/v1/members/**