server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/books/**

        - id: member-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/members/**